const HARVEST_TOKEN = process.env.HARVEST_TOKEN; 
const HARVEST_ACCOUNT_ID = process.env.HARVEST_ACCOUNT_ID;
const HARVEST_USER_ID = process.env.HARVEST_USER_ID;

module.exports = {
  HARVEST_TOKEN,
  HARVEST_ACCOUNT_ID,
  HARVEST_USER_ID
};
